<a href="https://colab.research.google.com/github/NhanPhamQuang/Math-Foundation-HK-243-Linear-Algebra/blob/main/Linear_Algebra_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

1. Prove that the transpose of the transpose of a matrix is the matrix itself: $(\mathbf{A}^\top)^\top = \mathbf{A}$.

In [ ]:
import torch

# Create a sample tensor
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

# Compute the transpose of A
A_T = A.t()

# Compute the transpose of A_T
A_T_T = A_T.t()

# Verify that A_T_T equals A
is_equal = torch.equal(A, A_T_T)

print("Original tensor A:")
print(A)
print("\nTranspose of A (A^T):")
print(A_T)
print("\nTranspose of A^T ((A^T)^T):")
print(A_T_T)
print("\nIs (A^T)^T equal to A?", is_equal)

Original tensor A:
tensor([[1, 2, 3],
        [4, 5, 6]])

Transpose of A (A^T):
tensor([[1, 4],
        [2, 5],
        [3, 6]])

Transpose of A^T ((A^T)^T):
tensor([[1, 2, 3],
        [4, 5, 6]])

Is (A^T)^T equal to A? True


2. Given two matrices $\mathbf{A}$ and $\mathbf{B}$, show that sum and transposition commute: $\mathbf{A}^\top + \mathbf{B}^\top = (\mathbf{A} + \mathbf{B})^\top$.

In [ ]:
# Create two sample tensors
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
B = torch.tensor([[7, 8, 9],
                  [10, 11, 12]])

# Compute A^T + B^T
A_T = A.t()  # Transpose for 2D tensor
B_T = B.t()
left_side = A_T + B_T

# Compute (A + B)^T
A_plus_B = A + B
right_side = A_plus_B.t()

# Verify equality
is_equal = torch.equal(left_side, right_side)

print("Tensor A:")
print(A)
print("\nTensor B:")
print(B)
print("\nA^T + B^T:")
print(left_side)
print("\n(A + B)^T:")
print(right_side)
print("\nIs A^T + B^T equal to (A + B)^T?", is_equal)

Tensor A:
tensor([[1, 2, 3],
        [4, 5, 6]])

Tensor B:
tensor([[ 7,  8,  9],
        [10, 11, 12]])

A^T + B^T:
tensor([[ 8, 14],
        [10, 16],
        [12, 18]])

(A + B)^T:
tensor([[ 8, 14],
        [10, 16],
        [12, 18]])

Is A^T + B^T equal to (A + B)^T? True


3. Given any square matrix $\mathbf{A}$, is $\mathbf{A} + \mathbf{A}^\top$ always symmetric? Can you prove the result by using only the results of the previous two exercises?

In [ ]:
# Create a sample square matrix
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Compute A + A^T
A_T = A.t()
sum_A_AT = A + A_T

# Check if A + A^T is symmetric by comparing with its transpose
sum_A_AT_T = sum_A_AT.t()
is_symmetric = torch.equal(sum_A_AT, sum_A_AT_T)

print("Matrix A:")
print(A)
print("\nA + A^T:")
print(sum_A_AT)
print("\nTranspose of (A + A^T):")
print(sum_A_AT_T)
print("\nIs A + A^T symmetric?", is_symmetric)

Matrix A:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

A + A^T:
tensor([[ 2,  6, 10],
        [ 6, 10, 14],
        [10, 14, 18]])

Transpose of (A + A^T):
tensor([[ 2,  6, 10],
        [ 6, 10, 14],
        [10, 14, 18]])

Is A + A^T symmetric? True


4. We defined the tensor `X` of shape (2, 3, 4) in this section. What is the output of `len(X)`? Write your answer without implementing any code, then check your answer using code.

In [ ]:
# Define a tensor X with shape (2, 3, 4)
X = torch.randn(2, 3, 4)

# Compute len(X)
length = len(X)

print("Tensor X shape:", X.shape)
print("len(X):", length)

Tensor X shape: torch.Size([2, 3, 4])
len(X): 2


In [ ]:
# Define a tensor X with shape (2, 3, 4)
X = torch.tensor([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
                  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])

# Compute len(X)
length = len(X)

print("Tensor X shape:", X.shape)
print("len(X):", length)

Tensor X shape: torch.Size([2, 3, 4])
len(X): 2


5. For a tensor `X` of arbitrary shape, does `len(X)` always correspond to the length of a certain axis of `X`? What is that axis?

In [ ]:
# Create tensors with different shapes
X1 = torch.randn(2, 3, 4)  # 3D tensor
X2 = torch.randn(5)        # 1D tensor
X3 = torch.randn(4, 2)     # 2D tensor
X4 = torch.randn(3, 2, 5, 6)  # 4D tensor

# Compute len() for each tensor and compare with size of first axis
print("Tensor X1 shape:", X1.shape, "len(X1):", len(X1), "First axis size:", X1.shape[0])
print("Tensor X2 shape:", X2.shape, "len(X2):", len(X2), "First axis size:", X2.shape[0])
print("Tensor X3 shape:", X3.shape, "len(X3):", len(X3), "First axis size:", X3.shape[0])
print("Tensor X4 shape:", X4.shape, "len(X4):", len(X4), "First axis size:", X4.shape[0])

Tensor X1 shape: torch.Size([2, 3, 4]) len(X1): 2 First axis size: 2
Tensor X2 shape: torch.Size([5]) len(X2): 5 First axis size: 5
Tensor X3 shape: torch.Size([4, 2]) len(X3): 4 First axis size: 4
Tensor X4 shape: torch.Size([3, 2, 5, 6]) len(X4): 3 First axis size: 3


7. When traveling between two points in downtown Manhattan, what is the distance that you need to cover in terms of the coordinates, i.e., in terms of avenues and streets? Can you travel diagonally?

In [ ]:
# Define two points in Manhattan grid (avenue, street)
point1 = torch.tensor([3, 5])  # (avenue, street)
point2 = torch.tensor([7, 8])

# Calculate Manhattan distance: |x2 - x1| + |y2 - y1|
manhattan_distance = torch.sum(torch.abs(point2 - point1))

# Output results
print("Point 1 (avenue, street):", point1)
print("Point 2 (avenue, street):", point2)
print("Manhattan distance (avenues + streets):", manhattan_distance.item())
print("Diagonal travel possible? No, restricted to grid lines.")

Point 1 (avenue, street): tensor([3, 5])
Point 2 (avenue, street): tensor([7, 8])
Manhattan distance (avenues + streets): 7
Diagonal travel possible? No, restricted to grid lines.


8. Consider a tensor of shape (2, 3, 4). What are the shapes of the summation outputs along axes 0, 1, and 2?

In [ ]:
# Create a tensor with shape (2, 3, 4)
X = torch.randn(2, 3, 4)

# Compute sums along axes 0, 1, and 2
sum_axis0 = X.sum(axis=0)
sum_axis1 = X.sum(axis=1)
sum_axis2 = X.sum(axis=2)

# Print shapes
print("Original tensor shape:", X.shape)
print("Shape of sum along axis 0:", sum_axis0.shape)
print("Shape of sum along axis 1:", sum_axis1.shape)
print("Shape of sum along axis 2:", sum_axis2.shape)

Original tensor shape: torch.Size([2, 3, 4])
Shape of sum along axis 0: torch.Size([3, 4])
Shape of sum along axis 1: torch.Size([2, 4])
Shape of sum along axis 2: torch.Size([2, 3])


9. Feed a tensor with three or more axes to the `linalg.norm` function and observe its output. What does this function compute for tensors of arbitrary shape?

In [ ]:
# Create a tensor with shape (2, 3, 4)
X = torch.randn(2, 3, 4)

# Compute the Frobenius norm
norm = torch.linalg.norm(X)

# Compute norm along specific axes (e.g., axis=(1, 2)) for comparison
norm_axes = torch.linalg.norm(X, dim=(1, 2))

print("Tensor X shape:", X.shape)
print("Tensor X:")
print(X)
print("Frobenius norm of X:", norm.item())
print("Norm along axes (1, 2) shape:", norm_axes.shape)
print("Norm along axes (1, 2):", norm_axes)

Tensor X shape: torch.Size([2, 3, 4])
Tensor X:
tensor([[[-0.4086, -0.8933,  0.3617, -1.1050],
         [-0.0902,  0.9664, -0.3586, -0.6783],
         [-0.5909, -0.4524,  1.0552, -1.1534]],

        [[-2.4534, -0.2908,  0.8685,  0.5183],
         [-0.6063, -0.4720,  2.0130,  0.0468],
         [-1.8592,  1.2989, -0.4654,  1.3795]]])
Frobenius norm of X: 5.087274551391602
Norm along axes (1, 2) shape: torch.Size([2])
Norm along axes (1, 2): tensor([2.6164, 4.3629])


10. Consider three large matrices, say $\mathbf{A} \in \mathbb{R}^{2^{10} \times 2^{16}}$, $\mathbf{B} \in \mathbb{R}^{2^{16} \times 2^{5}}$ and $\mathbf{C} \in \mathbb{R}^{2^{5} \times 2^{14}}$, initialized with Gaussian random variables. You want to compute the product $\mathbf{A} \mathbf{B} \mathbf{C}$. Is there any difference in memory footprint and speed, depending on whether you compute $(\mathbf{A} \mathbf{B}) \mathbf{C}$ or $\mathbf{A} (\mathbf{B} \mathbf{C})$. Why?

In [ ]:
import torch
import time

# Define matrix dimensions
n1, n2, n3, n4 = 2**10, 2**16, 2**5, 2**14

# Create large matrices with Gaussian random variables
A = torch.randn(n1, n2, dtype=torch.float32, device='cuda' if torch.cuda.is_available() else 'cpu')
B = torch.randn(n2, n3, dtype=torch.float32, device='cuda' if torch.cuda.is_available() else 'cpu')
C = torch.randn(n3, n4, dtype=torch.float32, device='cuda' if torch.cuda.is_available() else 'cpu')

# Function to measure memory and time
def measure_operation(func, name):
    torch.cuda.empty_cache() if torch.cuda.is_available() else None
    start_time = time.time()
    result = func()
    end_time = time.time()
    # Estimate memory usage of intermediate and final results
    memory_bytes = result.element_size() * result.numel()
    if torch.cuda.is_available():
        peak_memory = torch.cuda.max_memory_allocated() / 1024**2  # MB
    else:
        peak_memory = "N/A (CPU)"
    print(f"{name} - Time: {end_time - start_time:.4f} seconds, Output shape: {result.shape}, "
          f"Output memory: {memory_bytes / 1024**2:.2f} MB, Peak memory: {peak_memory} MB")
    return result

# Compute (A B) C
def compute_ABC():
    AB = torch.matmul(A, B)
    return torch.matmul(AB, C)

# Compute A (B C)
def compute_A_BC():
    BC = torch.matmul(B, C)
    return torch.matmul(A, BC)

# Run and measure both computations
print("Computing (A B) C:")
result1 = measure_operation(compute_ABC, "(A B) C")
print("\nComputing A (B C):")
result2 = measure_operation(compute_A_BC, "A (B C)")

# Verify results are equivalent
is_equal = torch.allclose(result1, result2, atol=1e-5)
print("\nAre results equal?", is_equal)

Computing (A B) C:
(A B) C - Time: 0.1379 seconds, Output shape: torch.Size([1024, 16384]), Output memory: 64.00 MB, Peak memory: N/A (CPU) MB

Computing A (B C):
A (B C) - Time: 36.7092 seconds, Output shape: torch.Size([1024, 16384]), Output memory: 64.00 MB, Peak memory: N/A (CPU) MB

Are results equal? False


11. Consider three large matrices, say $\mathbf{A} \in \mathbb{R}^{2^{10} \times 2^{16}}$, $\mathbf{B} \in \mathbb{R}^{2^{16} \times 2^{5}}$ and $\mathbf{C} \in \mathbb{R}^{2^{5} \times 2^{16}}$. Is there any difference in speed depending on whether you compute $\mathbf{A} \mathbf{B}$ or $\mathbf{A} \mathbf{C}^\top$? Why? What changes if you initialize $\mathbf{C} = \mathbf{B}^\top$ without cloning memory? Why?

In [ ]:
# Define matrix dimensions
n1, n2, n3 = 2**10, 2**16, 2**5  # 1024, 65536, 32

# Create matrices with Gaussian random variables
A = torch.randn(n1, n2, dtype=torch.float32, device='cuda' if torch.cuda.is_available() else 'cpu')
B = torch.randn(n2, n3, dtype=torch.float32, device='cuda' if torch.cuda.is_available() else 'cpu')
C = torch.randn(n3, n2, dtype=torch.float32, device='cuda' if torch.cuda.is_available() else 'cpu')

# Function to measure time and memory
def measure_operation(func, name):
    torch.cuda.empty_cache() if torch.cuda.is_available() else None
    start_time = time.time()
    result = func()
    end_time = time.time()
    memory_bytes = result.element_size() * result.numel()
    peak_memory = torch.cuda.max_memory_allocated() / 1024**2 if torch.cuda.is_available() else "N/A (CPU)"
    print(f"{name} - Time: {end_time - start_time:.4f} seconds, Output shape: {result.shape}, "
          f"Output memory: {memory_bytes / 1024**2:.2f} MB, Peak memory: {peak_memory} MB")
    return result

# Compute A B
def compute_AB():
    print(f"A shape: {A.shape}, B shape: {B.shape}")
    return torch.matmul(A, B)

# Compute A C^T
def compute_A_CT():
    print(f"A shape: {A.shape}, C^T shape: {C.t().shape}")
    return torch.matmul(A, C.t())

# Compute A C^T with C = B^T (no cloning)
def compute_A_BT():
    C_BT = B.t()  # C = B^T, no cloning
    print(f"A shape: {A.shape}, C (=B^T) shape: {C_BT.shape}, C^T shape: {C_BT.t().shape}")
    return torch.matmul(A, C_BT.t())  # Use C^T = (B^T)^T = B

# Run and measure computations
print("Computing A B:")
result_AB = measure_operation(compute_AB, "A B")
print("\nComputing A C^T:")
result_A_CT = measure_operation(compute_A_CT, "A C^T")
print("\nComputing A C^T with C = B^T (no cloning):")
result_A_BT = measure_operation(compute_A_BT, "A (C^T) where C = B^T")

# Verify results when C = B^T
C = B.t()  # Set C as B^T without cloning
is_equal = torch.allclose(result_AB, result_A_BT, atol=1e-5)
print("\nIs A B equal to A (C^T) when C = B^T?", is_equal)

Computing A B:
A shape: torch.Size([1024, 65536]), B shape: torch.Size([65536, 32])
A B - Time: 0.0915 seconds, Output shape: torch.Size([1024, 32]), Output memory: 0.12 MB, Peak memory: N/A (CPU) MB

Computing A C^T:
A shape: torch.Size([1024, 65536]), C^T shape: torch.Size([65536, 32])
A C^T - Time: 0.1032 seconds, Output shape: torch.Size([1024, 32]), Output memory: 0.12 MB, Peak memory: N/A (CPU) MB

Computing A C^T with C = B^T (no cloning):
A shape: torch.Size([1024, 65536]), C (=B^T) shape: torch.Size([32, 65536]), C^T shape: torch.Size([65536, 32])
A (C^T) where C = B^T - Time: 0.0924 seconds, Output shape: torch.Size([1024, 32]), Output memory: 0.12 MB, Peak memory: N/A (CPU) MB

Is A B equal to A (C^T) when C = B^T? True


12. Consider three matrices, say $\mathbf{A}, \mathbf{B}, \mathbf{C} \in \mathbb{R}^{100 \times 200}$. Construct a tensor with three axes by stacking $[\mathbf{A}, \mathbf{B}, \mathbf{C}]$. What is the dimensionality? Slice out the second coordinate of the third axis to recover $\mathbf{B}$. Check that your answer is correct.

In [ ]:
# Create three matrices A, B, C with shape (100, 200)
A = torch.randn(100, 200)
B = torch.randn(100, 200)
C = torch.randn(100, 200)

# Stack matrices to create a tensor with shape (3, 100, 200)
tensor = torch.stack([A, B, C], dim=0)

# Get the dimensionality of the tensor
tensor_shape = tensor.shape

# Slice out the second coordinate of the first axis (index 1) to recover B
B_recovered = tensor[1]

# Check if B_recovered matches B
is_equal = torch.equal(B, B_recovered)

# Print results
print("Tensor shape:", tensor_shape)
print("Shape of B_recovered:", B_recovered.shape)
print("Is B_recovered equal to B?", is_equal)

Tensor shape: torch.Size([3, 100, 200])
Shape of B_recovered: torch.Size([100, 200])
Is B_recovered equal to B? True
