In [7]:
import torch

In [8]:
# 1. Scalars
# Example: Calculate Body Mass Index (BMI)
# Compute BMI using weight and height as scalars.

# Scalars for weight (kg) and height (m)
weight = torch.tensor(70.0)
height = torch.tensor(1.75)

# Calculate BMI: weight / (height^2)
bmi = weight / (height ** 2)

print(f"Weight: {weight.item()} kg")
print(f"Height: {height.item()} m")
print(f"BMI: {bmi.item():.2f}")

Weight: 70.0 kg
Height: 1.75 m
BMI: 22.86


In [9]:
# 2. Vectors
# Example: Calculate Total Calories Burned
# Represent daily exercise durations as a vector and compute total calories burned.

# Vector of exercise durations (hours) and calories per hour
durations = torch.tensor([0.5, 1.0, 0.75])  # [running, cycling, swimming]
calories_per_hour = torch.tensor([600.0, 400.0, 500.0])

# Total calories: elementwise multiplication and sum
total_calories = (durations * calories_per_hour).sum()

print(f"Exercise Durations: {durations} hours")
print(f"Calories per Hour: {calories_per_hour} kcal/hour")
print(f"Total Calories Burned: {total_calories.item():.2f} kcal")

Exercise Durations: tensor([0.5000, 1.0000, 0.7500]) hours
Calories per Hour: tensor([600., 400., 500.]) kcal/hour
Total Calories Burned: 1075.00 kcal


In [10]:
# 3. Matrices
# Example: Sales Data Analysis
# Represent monthly sales data for products and compute total sales per product.

# Matrix: rows (products), columns (months)
sales = torch.tensor([[100.0, 120.0, 110.0],  # Product A
                      [80.0, 90.0, 85.0],    # Product B
                      [150.0, 130.0, 140.0]]) # Product C

# Total sales per product (sum along axis 1)
total_sales = sales.sum(axis=1)

print(f"Sales Matrix:\n{sales}")
print(f"Total Sales per Product: {total_sales}")

Sales Matrix:
tensor([[100., 120., 110.],
        [ 80.,  90.,  85.],
        [150., 130., 140.]])
Total Sales per Product: tensor([330., 255., 420.])


In [11]:
# 4. Tensors
# Example: Batch of Grayscale Images
# Create a 3rd-order tensor for a batch of grayscale images.

# 3rd-order tensor: [batch, height, width]
images = torch.ones(2, 3, 3) * torch.tensor([[[1.0]], [[2.0]]])  # Two 3x3 images

# Access a pixel
pixel = images[0, 1, 1]

print(f"Grayscale Images:\n{images}")
print(f"Pixel (1,1) in first image: {pixel.item()}")
print(f"Tensor Shape: {images.shape}")

Grayscale Images:
tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]]])
Pixel (1,1) in first image: 1.0
Tensor Shape: torch.Size([2, 3, 3])


In [13]:
# 5. Basic Properties of Tensor Arithmetic
# Example: Image Contrast Adjustment
# Adjust the contrast of an image by scaling pixel values.

# Grayscale image (2D tensor)
image = torch.tensor([[100.0, 150.0], [200.0, 250.0]])

# Adjust contrast by scaling
contrast_factor = 1.2
adjusted_image = image * contrast_factor

print(f"Original Image:\n{image}")
print(f"Contrast-Adjusted Image:\n{adjusted_image}")

Original Image:
tensor([[100., 150.],
        [200., 250.]])
Contrast-Adjusted Image:
tensor([[120.0000, 180.0000],
        [240.0000, 300.0000]])


In [14]:
# 6. Reduction
# Example: Average Exam Scores
# Compute average scores across subjects for students.

# Matrix: rows (students), columns (subjects)
scores = torch.tensor([[85.0, 90.0, 88.0],
                       [78.0, 82.0, 80.0]])

# Average score per student (axis 1)
avg_scores = scores.mean(axis=1)

print(f"Scores Matrix:\n{scores}")
print(f"Average Scores per Student: {avg_scores}")

Scores Matrix:
tensor([[85., 90., 88.],
        [78., 82., 80.]])
Average Scores per Student: tensor([87.6667, 80.0000])


In [15]:
# 7. Non-Reduction Sum
# Example: Normalize Sales Data
# Normalize sales so each product’s monthly sales sum to 1.

# Sales matrix: rows (products), columns (months)
sales = torch.tensor([[100.0, 120.0, 110.0],
                      [80.0, 90.0, 85.0]])

# Non-reduction sum along axis 1
sum_sales = sales.sum(axis=1, keepdims=True)

# Normalize
normalized_sales = sales / sum_sales

print(f"Sales Matrix:\n{sales}")
print(f"Sum per Product:\n{sum_sales}")
print(f"Normalized Sales:\n{normalized_sales}")

Sales Matrix:
tensor([[100., 120., 110.],
        [ 80.,  90.,  85.]])
Sum per Product:
tensor([[330.],
        [255.]])
Normalized Sales:
tensor([[0.3030, 0.3636, 0.3333],
        [0.3137, 0.3529, 0.3333]])


In [16]:
# 8. Dot Products
# Example: Weighted Exam Score
# Calculate a student’s weighted exam score.

# Scores and weights
scores = torch.tensor([85.0, 90.0, 88.0])
weights = torch.tensor([0.4, 0.3, 0.3])

# Dot product
weighted_score = torch.dot(scores, weights)

print(f"Scores: {scores}")
print(f"Weights: {weights}")
print(f"Weighted Score: {weighted_score.item():.2f}")

Scores: tensor([85., 90., 88.])
Weights: tensor([0.4000, 0.3000, 0.3000])
Weighted Score: 87.40


In [17]:
# 9. Matrix–Vector Products
# Example: Neural Network Layer
# Simulate a neural network layer’s output.

# Weight matrix and input vector
weights = torch.tensor([[0.5, 0.3], [0.2, 0.4]])  # 2 neurons, 2 inputs
inputs = torch.tensor([1.0, 2.0])

# Compute output
output = torch.mv(weights, inputs)

print(f"Weights:\n{weights}")
print(f"Inputs: {inputs}")
print(f"Layer Output: {output}")

Weights:
tensor([[0.5000, 0.3000],
        [0.2000, 0.4000]])
Inputs: tensor([1., 2.])
Layer Output: tensor([1.1000, 1.0000])


In [18]:
# 10. Matrix–Matrix Multiplication
# Example: Neural Network Layer Composition
# Compose two neural network layers.

# Two layer weight matrices
layer1 = torch.tensor([[0.5, 0.3], [0.2, 0.4]])
layer2 = torch.tensor([[0.1, 0.6], [0.7, 0.2]])

# Compose layers
composition = torch.mm(layer1, layer2)

print(f"Layer 1 Weights:\n{layer1}")
print(f"Layer 2 Weights:\n{layer2}")
print(f"Composed Weights:\n{composition}")

Layer 1 Weights:
tensor([[0.5000, 0.3000],
        [0.2000, 0.4000]])
Layer 2 Weights:
tensor([[0.1000, 0.6000],
        [0.7000, 0.2000]])
Composed Weights:
tensor([[0.2600, 0.3600],
        [0.3000, 0.2000]])


In [19]:
# 11. Norms
# Example 1: Error in Predictions
# Compute L1 and L2 norms of prediction errors.

# Predicted and actual values
predicted = torch.tensor([2.5, 0.0, 2.1])
actual = torch.tensor([3.0, -0.5, 2.0])

# Error vector
error = predicted - actual

# L1 and L2 norms
l1_norm = torch.abs(error).sum()
l2_norm = torch.norm(error)

print(f"Predicted: {predicted}")
print(f"Actual: {actual}")
print(f"Error: {error}")
print(f"L1 Norm: {l1_norm.item():.2f}")
print(f"L2 Norm: {l2_norm.item():.2f}")

Predicted: tensor([2.5000, 0.0000, 2.1000])
Actual: tensor([ 3.0000, -0.5000,  2.0000])
Error: tensor([-0.5000,  0.5000,  0.1000])
L1 Norm: 1.10
L2 Norm: 0.71


In [20]:
# Example 2: Matrix Regularization
# Compute the Frobenius norm of a weight matrix for regularization.

# Weight matrix
weights = torch.tensor([[0.5, 0.3], [0.2, 0.4]])

# Frobenius norm
frobenius_norm = torch.norm(weights)

print(f"Weights:\n{weights}")
print(f"Frobenius Norm: {frobenius_norm.item():.2f}")

Weights:
tensor([[0.5000, 0.3000],
        [0.2000, 0.4000]])
Frobenius Norm: 0.73
